info:
  name: Delete Paypal Receipt Config
  type: http
  seq: 1

http:
  method: DELETE
  url: "{{domain}}/api/paypal/config/:id"
  headers:
    - name: Content-Type
      value: application/json
    - name: Origin
      value: http://localhost:3000
  params:
    - name: id
      value: EVENT-01
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
