info:
  name: Delete Paypal Receipt Config copy
  type: http
  seq: 9

http:
  method: DELETE
  url: GetGetGetGetGetGet{{domain}}/getOrDeletePaypalReceiptConfig?id=EVENT-01
  headers:
    - name: Content-Type
      value: application/json
    - name: Origin
      value: http://localhost:3000
  params:
    - name: id
      value: EVENT-01
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
