info:
  name: Upsert Paypal Receipt config
  type: http
  seq: 7

http:
  method: PUT
  url: "{{domain}}/upsertPaypalReceiptConfig"
  headers:
    - name: Content-Type
      value: application/json
    - name: Origin
      value: http://localhost:3000
  body:
    type: json
    data: |-
      {
        "paypalItemId": "EVENT-01",
        "receiptAmountFactor": 0
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
